### ISSUE TITLE
kusama shell parathread preparation.

### ISSUE THREAD

**Issue by clangenb** [integritee-network/parachain#4] opened 2021-06-13 14:42 UTC
- [x] bump to polkadot-v0.9.4
- [x] prepare shell runtime
- [x] bump to cumulus-v0.9.7 #14 
- [x] bump to cumulus-v0.9.8 #23 
- [x] test runtime upgrade to integritee
- [x] #35 
- [x] test-on-westend

# Manual test procedure
1. launch rococo-local relay-chain (polkadot `v0.9.3-local-testing` with polkadot-launch `cbb4373` without any parachains)
2. download DUT shell.wasm and shell.state from CI artifacts
3. register parathread with id 2015 (shell.wasm and state)
4. verify 
   a. sudo key
   b. sudo has 10MTEER
   c. total supply is 10MTEER
   d. paraid is 2015
5. perform token transaction (must pay fees)
6. download integritee.wasm and integritee.state from CI artifacts
6. sudo->system->setCode(integritee)
7. verify same as above
8. verify: produces blocks
8. post permalink to tested artifacts in this thread

**Comment by clangenb** [comment] 2021-06-18 16:43
Tested everything according to this protocol: https://github.com/scs/integritee-parachain/blob/edca34334246b9f7595eb170332f1d7e7e965f96/parathread_registration_test_protocol.md

The tested artifacts are mentioned there. But if you want, I can recite them here.

**Comment by brenzi** [comment] 2021-06-19 10:42
I was able to test with integritee keys, starting an extra collator with 
```
/target/release/integritee-collator --collator -d /tmp/teerk1/integritee_test --parachain-id 2015 --chain shell-rococo-local.json --port 40335 --ws-port 9946 --rpc-port 9936 -- --execution wasm --chain rococo-local-raw.json --port 30337 --ws-port 9981
```
and then injecting the Aura key with `author_insertKey`

With a single collator, the block time is 60s (5 x target 12) as all others are skipped. But liveness is there even with 1 collator

**Comment by brenzi** [comment] 2021-06-19 13:46
Will now test 
srtool shell.wasm and .state from same commit as @clangenb tested above: 0c699837577fec7baa92698fd3b81d4ae6709a3f

**Comment by clangenb** [comment] 2021-06-20 07:28
I could successfully produce blocks with:

* shell.wasm (srtool) https://github.com/scs/integritee-parachain/suites/3030614118/artifacts/68758718
* shell-rococo-local-dev.state: https://github.com/scs/integritee-parachain/suites/3030614115/artifacts/68761359
* collator: https://github.com/scs/integritee-parachain/suites/3030614115/artifacts/68761343

However, I could not produce blocks with the integritee keys according to the above procedure - neither for the srtool wasm, nor the artifacts of https://github.com/scs/integritee-parachain/commit/0c699837577fec7baa92698fd3b81d4ae6709a3f.

**Comment by brenzi** [comment] 2021-06-20 11:49
tried again, with locally built binary and srtool wasm. It worked with commit d9a647d8fdbaa4a8166ec1785509c86e570cfb94 where I have only one custom authority which is endowed. But because shell-rococo-local.json sets chainType to Local, js/apps won't behave as expected. should be Live, because only "-dev" is Local in our case

**Comment by brenzi** [comment] 2021-06-20 14:30
# setup
* integritee-collator 0.6.0-970cc1c-x86_64-linux-gnu
* polkadot-launch @a017b95ca153519c086bc6fdc5c063b0dde8495f
* polkadot 0.9.3-8a3d93591-x86_64-linux-gnu
(v0.9.3-local-testing)

run
```
scripts/dump_wasm_and_state_for_all_chains.sh
```

and get 
* shell.wasm (srtool): https://github.com/scs/integritee-parachain/suites/3030614118/artifacts/68758718

```
sha256sum 
e1604dc539a298900cef498216c8e87e641e4e71051f3c3107995d03ab31a59f  shell-srtool-0c69983.wasm
```

launch relaychain
```
node ../polkadot-launch/dist/index.js launch-rococo-local.json
```

register paraid until 2015

register parathread with id 2015
* shell-srtool-0c69983.wasm
* shell-kusama.state 

launch collator
```
./target/release/integritee-collator --collator -d /tmp/teerk1/integritee_test --parachain-id 2015 --chain shell-rococo-local.json --port 40335 --ws-port 9946 --rpc-port 9936 -- --execution wasm --chain rococo-local-raw.json --port 30337 --ws-port 9981
```

sudo > paraSudoWrapper > upgradeParachain

inject collator aura key
```
curl http://localhost:9936 -H "Content-Type:application/json;charset=utf-8" -d '{ "jsonrpc":"2.0", "id":1, "method":"author_insertKey", "params": [ "aura", "<MNEMONIC>", "0xc6c1370a5b6656f3816b2a6c32444ec18d5ac6d33103c4e5c3f359623a19dc47" ] }'
```

js-apps on 9946 now identifies as:
```
IntegriTEE Shell (Local)
integritee-parachain/0
#6
```

block time target is 12s, really is 12s

transfer of funds works

vesting > vestingTransfer
* target : Bob
* locked: 100
* perBlock= 1
* staring=50

success:
* Bob's account shows 100, transferrable 0, locked 100
* at block 51, transferrable 0, vested 1, locked 100
* vested counting up 

chain upgrade: 
extrinsics: sudo > sudoUncheckdWeight > system > setCode(<integritee-kusama.wasm>)

js/apps after reload now identifies as 
IntegriTEE Shell (Local)
integritee-parachain/9
#73

we need to restart the collator to fix the name:
```
./target/release/integritee-collator --collator -d /tmp/teerk1/integritee_test --parachain-id 2015 --chain integritee-rococo-local.json --port 40335 --ws-port 9946 --rpc-port 9936 -- --execution wasm --chain rococo-local-raw.json --port 30337 --ws-port 9981
```

then it looks like this:
```
IntegriTEE Network (Local)
integritee-parachain/9
#88
```

(this is actually indicating we're doing it wrong I think)

**SUCCESS!!**

**Comment by brenzi** [comment] 2021-06-21 19:48
[shell-tested-setup.zip](https://github.com/scs/integritee-parachain/files/6689125/shell-tested-setup.zip)

**Comment by clangenb** [comment] 2021-06-22 07:09
I am getting the error:

```
[Parachain] Could not find the header of the genesis block in the database! block_hash=0x296c4e2af69f78d5cd97a3da21554b05cbd7358004c0ad820787caec6cf0cab2
```

Which is due to a different genesis head from the one registered on the chain: https://github.com/paritytech/cumulus/issues/385

Indeed, I found the genesis state generated by my integritee-collator@970cc1c to be slightly different from the one of  `shell-tested-setup.zip`. This is most likely due to the nondeterministic rust build process.

So as your zip does not include the collator nor the `shell-rococo-local.spec` I can't confirm that it works.

**Comment by clangenb** [comment] 2021-06-22 07:41
However, I can confirm successful registration and block production with:

*  Artifact containing shell-kusama wasm,  state and the checksum of the two. [shell-kusama-67bcb13f98c298e98335802efbef244a2e162826](https://github.com/scs/integritee-parachain/suites/3050010585/artifacts/69349586).

* srtool shell runtime in the following artifact: [shell-runtime-67bcb13f98c298e98335802efbef244a2e162826](https://github.com/scs/integritee-parachain/suites/3050010576/artifacts/69344174)

```
sha256sum shell-runtime-srtool-67bcb13f98c298e98335802efbef244a2e162826
e1604dc539a298900cef498216c8e87e641e4e71051f3c3107995d03ab31a59f  shell-runtime-srtool-67bcb13f98c298e98335802efbef244a2e162826
```

* [integritee-collator-67bcb13f98c298e98335802efbef244a2e162826](https://github.com/scs/integritee-parachain/suites/3050010585/artifacts/69349585)

```
sha256sum integritee-collator
d7d19135a43e7ee4438538492ff5cf7bab10e0be62290df793e6aef9cc5a6956  integritee-collator
```

**Comment by brenzi** [comment] 2021-06-23 12:37
> I am getting the error:
> 
> ```
> [Parachain] Could not find the header of the genesis block in the database! block_hash=0x296c4e2af69f78d5cd97a3da21554b05cbd7358004c0ad820787caec6cf0cab2
> ```
> 
> Which is due to a different genesis head from the one registered on the chain: [paritytech#385](https://github.com/paritytech/cumulus/issues/385)
> 
> Indeed, I found the genesis state generated by my integritee-collator@970cc1c to be slightly different from the one of `shell-tested-setup.zip`. This is most likely due to the nondeterministic rust build process.
> 
> So as your zip does not include the collator nor the `shell-rococo-local.spec` I can't confirm that it works.

There must be a misunderstanding. The zip contains all you need. When registering the parathread, use 
* shell-srtool-0c69983.wasm
* shell-kusama-970cc1c.state
You can use shell-kusama as shell-rococo-local will be byte-equivalent if generated by the same binary

**Comment by clangenb** [comment] 2021-06-23 12:41
Yes, but there is no binary.

**Comment by brenzi** [comment] 2021-06-23 12:44
No, but that's the point: It must work with a different binary because people may compile it themselves. But I guess the problem is that shell-rococo-local-raw.json wasn't included. I updated the zip...
[shell-tested-setup.zip](https://github.com/integritee-network/parachain/files/6701867/shell-tested-setup.zip)

**Comment by clangenb** [comment] 2021-06-23 12:54
I agree that it must work with a different binary. 

But as you correctly concluded, I also need the `shell-rococo-local-raw.json` from your binary because I can't recreate it byte-equivalently with a different binary - which leads to the above error.

**Comment by brenzi** [comment] 2021-06-23 13:03
that's why the above attached zip now includes that file ;-)

**Comment by clangenb** [comment] 2021-06-23 13:55
I can confirm that it works for the 2nd version of the zip:

verified:
* block production equals 12s after injecting authority keys.
* total issuance == 10MTeer
* integritee-root account has 10MTeer

I think this is everything I can confirm without having the root key.

**Comment by brenzi** [comment] 2021-07-01 14:38
We need to redo these tests after #14 
and the runtime upgrade should be done using the `compact` wasm!

**Comment by brenzi** [comment] 2021-07-07 20:01
successful launch and upgrade on westend-local. :rocket: 
test protocol: https://gist.github.com/brenzi/9e45a60067342d8604899b241f789091

**Closed** 2021-09-07 10:12 UTC
